#!/usr/bin/env python3
"""SCAFFOLD -- not implemented yet. Split a RavenPack taxonomy into an
evergreen-like taxonomy and a garbage-catching taxonomy for the
garbage-vs-F0 benchmark described in the GFC/Covid scoring notebooks'
"Future work" section.

Goal
----
`Legacy/Vendor/RavenPack/vendor_taxonomy.csv` (or a newer RavenPack export)
is a single flat taxonomy of ~7,500 primitives with no evergreen/garbage
distinction and no paraphrase JSONLs. The plan is to split it into two named
taxonomies, each following the exact `Narrative_Taxonomy` monorepo layout
(see `narrative_scoring/taxonomy.py`) so they load through
`narrative_scoring.taxonomy.load_taxonomy` completely unmodified:

    Narrative_Taxonomy/
        {evergreen_name}_taxonomy.authored.csv
        {evergreen_name}-primitive_semantic_paraphrases.jsonl
        {evergreen_name}-primitive_headline_paraphrases.jsonl
        {garbage_name}_taxonomy.authored.csv
        {garbage_name}-primitive_semantic_paraphrases.jsonl
        {garbage_name}-primitive_headline_paraphrases.jsonl

Once both exist and are embedded (`scripts/embed_taxonomy.py`, once per
name), a garbage-catcher rejection layer needs to be reintroduced --
`narrative_scoring/garbage.py` and every `D_garbage`/`use_garbage` code path
were removed wholesale during the Narrative_Taxonomy monorepo migration
(too much work to redesign for the new layout at the time), not merely
disabled. Re-adding it is a second, separate piece of work from the split
itself: mirror `apply_garbage_filter`'s old contract (reject a headline that
scores higher against the garbage taxonomy than the real one) and wire it
back into `scoring.score_day` / `adhoc.score_window` alongside F0, the way
the removed "Substudy A" grid in the scoring notebooks compared
`(use_f0, use_garbage)` combinations.

Open questions this scaffold deliberately leaves unresolved
--------------------------------------------------------------
- **The split criterion.** The RavenPack CSV carries no is-garbage flag or
  similar column (checked: TOPIC, GROUP, TYPE, SUB_TYPE, ROLE, CATEGORY,
  DISPLAY_NAME, DESCRIPTION, SCHEDULED, VALID_ENTITY_TYPES, TAGS -- nothing
  usable directly). This needs either manual curation, a heuristic over
  TOPIC/GROUP/TAGS, or an LLM classification pass -- undecided.
- **Paraphrase generation.** Neither half will have semantic/headline
  paraphrase JSONLs to start; RavenPack's DESCRIPTION alone is not enough
  (Evergreen_v5's own paraphrases were generated by a separate, not-yet-
  ported pipeline). Producing K paraphrases per primitive x 2 styles for
  ~7,500 rows is its own project, out of scope for this scaffold.

Nothing below is implemented. Run this script and it will tell you so.
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

log = logging.getLogger(__name__)


def split_ravenpack_taxonomy(
    source_csv: Path,
    evergreen_name: str,
    garbage_name: str,
    out_root: Path,
) -> None:
    """Split source_csv's rows into two authored CSVs under out_root.

    TODO (see module docstring's "open questions"):
      1. Decide and implement the evergreen/garbage split criterion.
      2. Write {evergreen_name}_taxonomy.authored.csv and
         {garbage_name}_taxonomy.authored.csv (RavenPack-schema columns,
         DISPLAY_NAME/DESCRIPTION carried through from source_csv).
      3. Generate semantic + headline paraphrase JSONLs for both halves
         (a separate paraphrase-generation pipeline, not yet built).
      4. Validate both with narrative_scoring.taxonomy.load_taxonomy before
         calling this done.
    """
    raise NotImplementedError(
        "split_ravenpack_taxonomy is a scaffold -- see this script's module "
        "docstring for the plan and open questions. Not implemented yet."
    )


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--source-csv", type=Path,
        help="RavenPack authored taxonomy CSV to split "
        "(e.g. Legacy/Vendor/RavenPack/vendor_taxonomy.csv)",
    )
    ap.add_argument("--evergreen-name", help='e.g. "RavenPack_Evergreen_v1"')
    ap.add_argument("--garbage-name", help='e.g. "RavenPack_GarbageCatcher_v1"')
    ap.add_argument(
        "--out-root",
        help="Narrative_Taxonomy root to write into "
        "(defaults to $RAW_DATA_PATH/Narrative_Taxonomy)",
    )
    ap.add_argument("-v", "--verbose", action="store_true")

    args = ap.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    log.error(
        "this script is a scaffold, not implemented yet -- see its module "
        "docstring for the plan and open questions"
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
